[project]
name = "ipvs"
version = "0.0.1"
description = "IP verification system"
authors = [{ name = "Nerd1029", email = "ljbarajr@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
