[project]
name = "IP-Verification-System"
version = "0.0.1"
description = ""
authors = [{ name="Nerd1029", email="" }]
readme = "README.md"
requires-python = ">=3.13.2"
license = { text = "MIT" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
