name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # required for Trusted Publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi  # must match the environment used in your Trusted Publisher setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build the package
        working-directory: IP-Verification-System
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: IP-Verification-System/dist
